package ss.pentago.util;

/**
 * NameGenerator is meant to be used to randomly generates
 * names for bots.
 */
public class NameGenerator {

    private NameGenerator() {
    }

    private static final String[] NAMES = {
        "PENTAGOO VOODOO",
        "RANDO-MICE",
        "NAIVE KEITH",
        "PENTAKILLER",
        "TREE SURFER",
        "BOT BANE",
        "CODE BREATHER",
        "SINGULARITY",
        "WE ARE 5",
        "PENTAGRAM",
        "SEARCH DESTROY",
        "GOD BOT",
        "THE PURGER",
        "THE PRUNER",
        "ELDER TREE",
        "THE ORACLE",
        "THE PROPHET",
        "THE SEER",
        "MARBLED",
        "TUNNEL VISION",
        "INTO THE DEEP",
        "BOT RHYTHM",
        "5/4 TIME",
        "FIVEFOLD",
        "BETA BLOCKER",
        "O(5)",
        "MASKED BOT",
        "5 O' CLOCK",
        "CLOCKWISE DERVISH",
        "QUADRANT COMMANDANT",
        "SUBBOARD SUBMARINE",
        "TIC TAC GO",
        "OGATNEP",
        "BOARD HUNTER",
        "AUTOMATIC AGONY",
        "PROTOCOL FLASHBACKS",
        "ALICE IN BOT-LAND",
        "BOB THE BOT",
        "AI ON ACID",
        "EXCEPTIONAL BOT",
        "UNKNOWN BOT EXCEPTION",
        "BOT THROWER",
        "MARBLE THROWER",
        "MARBLE CATCHER",
        "SYSTEM.BOT",
        "CHECK MA STYLE",
        "WHO WINS? YOU DECIDE!",
        "THE GAME IS RIGGED",
        "BOARD STABBER",
        "AI 101",
        "BOT-O-LOGY",
        "AUTO PILOT",
        "BLACK BOX",
        "DEEP COPY DREAMER",
        "HELLO, PENTAGO",
        "I AM PENTAGO",
        "ALREADYLOGGEDIN",
        "NEWGAME NEWLIFE",
        "THE LAST SHALL BE THE FIRST",
        "THE FIRST SHALL BE THE LAST",
        "VENI VIDI VICI",
        "I CHALLENGE YOU TO SINGLE COMBAT",
        "HITTIN' ALL THE WRONG MOVES",
        "GOING SIDEWAYS",
        "TOP DOWN PERSPECTIVE",
        "CLUMSY CLIENT",
        "MATILDE MATILDA",
        "SYNTAX POLICE",
        "MULTI-LEVEL TREE SCHEME",
        "JOIN THE RESISTANCE, SAY NO TO PENTAGO",
        "I EAT MARBLES FOR BREAKFAST",
        "NESTING ESCALATION",
        "THE BOT-FATHER",
        "SUBBOARD SURFER",
        "CLASH OF CLIENTS",
        "LEAGUE OF LISTENERS",
        "BOT OF THE WILD",
        "FINAL STRATEGY XIV",
        "THREADED THREAT",
        "I, BOT",
        "SCHOLAR OF THE FIRST PING",
        "HOLD MY BOARD",
        "PYRAMID BOT",
        "BOTSLAYER69",
        "360 NO-PRUNING",
        "PSYCHO BOT",
        "BEGONE BOT",
        "PHANTOM BOT",
        "PROGRESSIVE BOT-CORE",
        "JUST ANOTHER RANDOMLY GENERATED NAME",
        "BABY BOT",
        "BOT ANNIHILATOR",
        "THEY MADE DOCUMENTATION ABOUT ME",
        "30 SECONDS OF FAME",
        "PEER-REVIEWED",
        "ROSES ARE BLACK, VIOLETS ARE WHITE",
        "THE BOARD IS LAVA",
        "BOTPUNK 55555",
        "NOT THREAD-SAFE FOR WORK",
        "THE POST-BOT ERA",
        "HUMAN-BOT FUSION",
        "PROGRAMMER SOCKETS"
    };

    /**
     * @return randomly generated bot username
     */
    public static String randomName() {
        return NAMES[Randomizer.randomInt(NAMES.length)];
    }
}
